# Brewfile (WSL / Homebrew-on-Linux) — reduced from the macOS Brewfile.
# Removed: all cask, vscode, cargo, and go entries; and macOS-only
# formulae. Core CLI tools also come from apt via setup.sh — use this only
# if you prefer managing the heavier dev tools with 'brew bundle'.
#   install:  brew bundle --file=Brewfile

tap "azure/functions"
tap "homebrew/services"
tap "iilonmasc/powerlevel9k", "https://github.com/iilonmasc/homebrew-powerlevel9k.git"
tap "jesseduffield/lazygit"
tap "mongodb/brew"
tap "stripe/stripe-cli"
tap "supabase/tap"

brew "openssl@3"
brew "azure-cli"
brew "bat"
brew "protobuf"
brew "bear"
brew "bob"
brew "cmake"
brew "libpq"
brew "composer"
brew "duckdb"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "glfw"
brew "glow"
brew "gnu-sed"
brew "htop"
brew "lazygit"
brew "leetsolv"
brew "llvm"
brew "luarocks"
brew "ninja"
brew "mongosh"
brew "node@16"
brew "openssl@1.1"
brew "pandoc"
brew "pipx"
brew "pngquant"
brew "poppler"
brew "postgresql@17", restart_service: :changed
brew "python@3.11"
brew "python@3.9"
brew "railway"
brew "raylib"
brew "redis"
brew "ripgrep"
brew "ruby", link: false
brew "telnet"
brew "tmux"
brew "tree"
brew "util-linux"
brew "wget"
brew "yt-dlp"
brew "zig"
brew "zls"
